### PR TITLE
Added root_device and candidate_devices to Proposal::Settings

### PR DESCRIPTION
**Pull request by ancorgs**
* Allows the caller to decide where / (and related partitions) is going to be installed.
* Knowing the root_device in advance allows BootRequirementsChecker to properly do its job.
* If root_device and candidate_device are not provided, they are calculated in a new additional first step.

### CODE REVIEW

**Comment by shundhammer** [comment]
Looks reasonable to me. Actually, I had expected a lot more impact with this change.

**Comment by gabi2** [comment]
For me the changes also make sense.

**Comment by ancorgs** [comment]
Updated. Only documentation is missing now.

**Comment by ancorgs** [comment]
Updated. Ready for review

**Comment by wfeldt** [comment]
I think it doesn't do what it intends to. (Or I'm missing some point.)

Anyway, I'll merge everything, so we can go on.

**Pull request merged**
