### PR TITLE
- adapted to new activate callbacks in libstorage-ng

### PR DESCRIPTION
**Pull request by aschnell**
See https://github.com/openSUSE/libstorage-ng/pull/481.

### CODE REVIEW

**Comment by ancorgs** [comment]
Not sure if I get the intention/meaning of the new argument.

**Comment by aschnell** [comment]
You can now activate multipath even if it does not look to be multipath. As it turns out the current multipath detection is not working always (e.g. when only one path is there while the detection is done).

**Comment by ancorgs** [comment]
But with this proposed PR we don't do it. So nothing has changed from the original bug point of view. Isn't it?

What are the implications of trying to activate multipath when there are no real multipath devices?

**Comment by aschnell** [comment]
Yes, right now we do not do it. But we might have to do it, e.g. depending on a boot parameter as suggested in the bug. I currently want to provide the possibility to avoid API changes later on, e.g. in an L3.

**Comment by joseivanlopez** [comment]
@ancorgs If I understood correctly, this PR only opens the possibility to use the param from the clients, but it does not try to change the current behavior. So, if something does not look a multipath, then multipath is not activated.

But maybe, even when something does not look a multipath, we should ask to the user, due to in some cases, the multipath is not correctly detected, so the user can decide.

**Comment by ancorgs** [comment]
@aschnell Ok. makes sense

@joseivanlopez No, I would not change the behavior now. Let's see how the discussion evolves.

**Comment by joseivanlopez** [comment]
@ancorgs Yes, I only comment it as a possibility. For now, I would keep the same behavior.

**Pull request merged**
