### PR TITLE
Use the improved Device.compare_by_name from libstorage-ng 

### PR DESCRIPTION
**Pull request by ancorgs**
Based on https://github.com/openSUSE/libstorage-ng/pull/400

Replaces https://github.com/yast/yast-storage-ng/pull/434 and #432

### CODE REVIEW

**Comment by ancorgs** [comment]
@aschnell yes

**Comment by aschnell** [comment]
@ancorgs I tried now, but no.

**Comment by ancorgs** [comment]
@aschnell Do you have a pull request or at least a diff with the changes in libstorage-ng, so I can check what breaks if yast-storage-ng?

**Comment by ancorgs** [comment]
@aschnell Just to clarify, does "_the remaining sorting of result_" mean all the `WhateverDevice.all` methods that were previously sorted using `compare_by_name`? In that case I don't think there is anything left and I believe everything works already.

Or does it means any sorting from any result, including more "local" stuff like `PartitionTable#partitions` (used to be sorted by partition number), `LvmVg#lvm_lvs` (used to be sorted by lv name) and so on? I didn't understand we wanted to go as far as "libstorage-ng will never sort any result" as part of this PBI, but adapting yast2-storage-ng for that should be a matter of 5 minutes (already tested locally) if that's the intention.

**Comment by aschnell** [comment]
The intension is indeed to not sort any return list/vectors anymore. To test this just remove the four sort calls in DevicegraphImpl.h (in the functions marked as to be deleted).

**Comment by ancorgs** [comment]
@aschnell Got it. I didn't understand we wanted to go that far as part of the current PBI, but here it is https://github.com/yast/yast-storage-ng/pull/456. I tested it as you suggested and everything looks sane to me.

**Comment by ancorgs** [comment]
@aschnell #456 is merged. Feel free to retry the sorting removal in the library.

**Pull request merged**
