### PR TITLE
encrypt: Fix UI message typo, loose->lose

### PR DESCRIPTION
**Pull request by sknorr**
## Problem

A typo in a UI message.

## Solution

Typo fixed. (I also slightly reworded the message below.)

## Testing

- Not tested but trivial, I guess

### CODE REVIEW

**Review by joseivanlopez — COMMENTED** [review]
Thanks for fixing it! The changes look ok to me, but the version should be bumped. Otherwise, the request will be rejected by our boots. Moreover, a new changelog entry is missing. Please, also add this reference in the changelog: "(part of jsc#SLE-21308)" .

**Comment by sknorr** [comment]
@joseivanlopez Thanks for the quick feedback, all fixed now I hope. (I also noticed that for some reason my branch was ~19 commits behind master ... not sure why--in any case, I rebased on top of master.)

**Review by joseivanlopez — APPROVED** [review]
LGTM

**Comment by joseivanlopez** [comment]
Merged, thanks!!

**Pull request merged**
